#authtoken: 
region: ap

tunnels:
  mySSH_server:
    addr: 22
    proto: tcp
  tcp1_server:
    addr: 8000
    proto: tcp
  serverHttp_server:
    addr: 80
    proto: http
    bind_tls: false
  serverHttps_server:
    addr: 81
    proto: http
    bind_tls: true
