#authtoken: 
region: ap

tunnels:
  mySSH_base:
    addr: 22
    proto: tcp
  tcp1_base:
    addr: 2102
    proto: tcp
  serverHttp_base:
    addr: 80
    proto: http
    bind_tls: false
  serverHttps_base:
    addr: 81
    proto: http
    bind_tls: true
